title: math2001's blog
baseURL: https://math2001.github.io
languageCode: en-au
metaDataFormat: yaml
preserveTaxonomyNames: true
publishBranch: master
newContentEditor: vim

theme: fasty
copyright: © Mathieu Paturel 2017-2019
enableEmoji: true

blackfriday:
  hrefTargetBlank: true

markup:
  highlight:
    codeFences: false

params:
  themefolderpath: themes/fasty
  sitecode: math2001/math2001.github.io
  logo:
    src: /img/math2001.svg
    alt: Round logo with a M in it (math2001's logo)
  favicon: img/math2001.png
  social:
    - username: _math2001
      name: twitter
      url: https://twitter.com/_math2001
    - username: math2001
      name: github
      url: https://github.com/math2001
    - username: math2001
      name: stackoverflow
      url: https://stackoverflow.com/users/6164984/math2001
    - username: math2001
      name: dev.to
      url: https://dev.com/math2001
    - username: math2001
      name: youtube
      url: https://www.youtube.com/channel/UCi2O717lLg8ugD5KxAJTwAQ

  footerbio: |
    French, lives in Australia, and gives computer instructions so they don't
    get bored. :smiley:

  home:
    name: Mathieu Paturel
    avatar:
      src: img/math2001.png
      alt: Picture of Mathieu Paturel
    bio: |
      Bonjour! I'm a prospective university student. I've been programming
      for about 4 years (self taught). I know a fair bit about Python, though
      I'm spending a lot more time writing Go these days... I also did a bit
      of web development.
    closing: |
      You are probably wondering what is the difference between a post, an
      article and a project. Articles and projects are carefully crafted,
      whereas posts are pretty much just me thinking out loud...
    links:
      - name: CV
        url: /cv.pdf
      - name: GitHub
        url: https://github.com/math2001

menu:
  footer:
    - name: Tags
      url: /tags
      weight: 1
    - name: Articles
      url: /article
      weigth: 5
    - name: Posts
      url: /post
      weigth: 10

